title: Main Street
author: Jared
email: n.a@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Im not really positive what I'm doing here but I want to let you know that
  things are happening. They're happening very fast. Hiyaku Ikiti!
  
  One more line! 

# social links
twitter_username: your-twitter-handle
github_username:  bubbleSoup

show_excerpts: false # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
